//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareable_data_generator
{
    using PropertyChanged;
    using System;
    using System.Collections.Generic;
    
    [AddINotifyPropertyChangedInterface]
    public partial class MainTable
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string ExcelName { get; set; }
        public string ColumnsWidth { get; set; }
        public string ColumnsName { get; set; }
        public string SQLstring { get; set; }
        public string ISYSview { get; set; }
        public string FolderPath { get; set; }
        public string FilePath { get; set; }
        public string ShareableLink { get; set; }
        public Nullable<System.DateTime> LastQuery { get; set; }
    }
}
